---
output:
  html_document:
    css: ['shared-styles.css']
---
```{r setup, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
knitr::opts_knit$set(root.dir = '../..')
```
```{r child='../shared/shared-header.rmd'}
```
***
```{r echo=FALSE, warning=FALSE, message=FALSE, dev='svg', results='asis'}
Sys.setenv(TZ=data$reportMetadata$timezone)

plots.tables.ALL <- uvhydrographPlot(data)

months_vec <- seq(as.Date(data[['reportMetadata']][['startDate']]), 
                  as.Date(data[['reportMetadata']][['endDate']]), 
                  by="month")
months_nm <- format(months_vec, "%b %Y")

noData_vec <- c()
for (i in seq_len(length(plots.tables.ALL))) {
  x <- plots.tables.ALL[[i]]
  if(!is.null(x$plot1)){
    noData_vec <- c(noData_vec, FALSE)
    printReportFeature(x$plot1)
    printReportFeature(x$table1, isTable=TRUE)
    printReportFeature(x$status_msg1, m=months_nm[i])
    printReportFeature(x$plot2)
    printReportFeature(x$table2, isTable=TRUE)
    printReportFeature(x$status_msg2, m=months_nm[i])
  } else {
    noData_vec <- c(noData_vec, TRUE)
  }
}


noData_msg <- paste("No data for:", paste(months_nm[which(noData_vec)], collapse=", "))

Sys.setenv(TZ="UTC")
```

#`r if(all(noData_vec)){paste("The dataset requested is empty.")}`#

#`r if(!all(noData_vec) & any(noData_vec)){paste(noData_msg)}`#

`r getSimsUrl(data)`
