---
output:
  html_document:
    includes:
      before_body: before.html
      after_body: after.html
    css: ['styles.css', 'shared-styles.css']
  pdf_document:
    includes:
      classoption: legalpaper, landscape
---
```{r setup, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
knitr::opts_knit$set(root.dir = '../..')
```
```{r child='../shared/shared-header.rmd'}
```
***
```{r,echo=FALSE,comment=NA,warning=FALSE,results='asis'}
tbl <- sensorreadingTable(data)
library(pander)
library(htmlTable)

if(!identical(tbl, "The dataset requested is empty.")){
  if (output=='pdf') {	 	
    pander(tbl$toRet, split.cell = 30, split.table = Inf) 
  } else {
    if(isNullOrFalse(data[['reportMetadata']][['excludeComments']])){
      rowColoring <- c("none", "none", "#F7F7F7", "#F7F7F7")
    } else {
      rowColoring <- c("none", "#F7F7F7")
    }
    
    pander(htmlTable(tbl$toRet, 
      cgroup=c("Field Visit Information","Reference Readings","Recorder Readings","Correction Information","Nearest IV"),
      n.cgroup=c(4,4,4,4,3),
      col.rgroup = rowColoring, 
      css.class = "table-cell",
      align="|rrrr|cccc|cccc|rrrr|rrr|",
      rnames=FALSE))
  }
}

```

***

```{r,echo=FALSE,result='asis',comment=NA,warning=FALSE}
if(!identical(tbl, "The dataset requested is empty.")){
  tbl2 <- srsQualifiersTable(data, tbl)
  if(!is.null(tbl2) && nrow(tbl2) > 0){
    htmlTable(tbl2,
                cgroup=c("Qualifiers"),
                n.cgroup=c(3),
                align="|lll|", 
                rnames=FALSE, 
                col.rgroup = c("none", "#F7F7F7"), css.cell = "padding-left: 1em; padding-right: 1em; padding-top:.5em;padding-bottom:.5em;")
  }
}
```

#`r if(identical(tbl, "The dataset requested is empty.")) {paste(tbl)}`#