language: c
# To build on OSX, switch the previous line to
# language: objective-c
cache: packages
sudo: required

script: ./travis-tool.sh run_tests

env:
  matrix:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-examples" R_CHECK_ARGS="--no-build-vignettes --no-manual --no-examples"

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh

install:
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh github_package usgs-r/gsplot#398
    - ./travis-tool.sh github_package jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change