# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki


language: r

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

r_github_packages:
 - usgs-r/gsplot#398
 - jimhester/covr
 
script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure: find *Rcheck -name '*.fail' -print -exec cat '{}' \;

notifications:
  email:
    on_success: change
    on_failure: change