# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki


language: r
cache: packages

env:
  global:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
    - r_build_args: "--no-manual --no-build-vignettes"
    - r_check_args: "--no-examples --no-manual --no-vignettes --no-build-vignettes"

r_github_packages:
 - usgs-r/gsplot#398
 - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change