# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki


language: r
sudo: false
cache: packages
r: 3.3.2

r_check_args: --no-examples

repos:
  CRAN: http://mran.microsoft.com/snapshot/2016-03-31
  MRAN1: http://mran.microsoft.com/snapshot/2016-01-27
  MRAN2: http://mran.microsoft.com/snapshot/2015-03-13

r_github_packages:
 - usgs-r/gsplot#398
 - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
  - cat '/home/travis/build/USGS-R/repgen/repgen.Rcheck/00check.log'

notifications:
  email:
    on_success: change
    on_failure: change
