language: r
r: 3.3.2
sudo: required
warnings_are_errors: false

cache: 
  packages: false

#r_check_args: --no-examples

install:
  #Remove Existing Packages
  - Rscript -e 'remove.packages("curl")' || true
  - Rscript -e 'remove.packages("knitr")' || true
  - Rscript -e 'remove.packages("rmarkdown")' || true
  - Rscript -e 'remove.packages("jsonlite")' || true
  - Rscript -e 'remove.packages("httr")' || true
  - Rscript -e 'remove.packages("magrittr")' || true
  - Rscript -e 'remove.packages("htmltools")' || true
  - Rscript -e 'remove.packages("caTools")' || true
  - Rscript -e 'remove.packages("RCurl")' || true
  - Rscript -e 'remove.packages("memoise")' || true
  - Rscript -e 'remove.packages("whisker")' || true
  - Rscript -e 'remove.packages("rstudioapi")' || true
  - Rscript -e 'remove.packages("roxygen2")' || true
  - Rscript -e 'remove.packages("devtools")' || true
  - Rscript -e 'remove.packages("dplyr")' || true
  - Rscript -e 'remove.packages("lubridate")' || true
  - Rscript -e 'remove.packages("htmlTable")' || true

  #Install First Set of Dependencies
  - Rscript -e 'install.packages(c("bitops","Rcpp","digest","magrittr","stringi","stringr","yaml","evaluate","formatr","highr","R6","assertthat","lazyeval","DBI","jsonlite","brew","mime","curl","caTools","openssl","memoise","whisker","rstudioapi","git2r","withr","markdown","knitr","htmltools", "rmarkdown","RCurl","htmlTable","roxygen2","dplyr","lubridate"), repos="http://mran.microsoft.com/snapshot/2016-03-31", type="source")'
  
  #Install a different version of HTTR
  - Rscript -e 'install.packages("httr", repos = "http://mran.microsoft.com/snapshot/2016-01-27",type="source")'
 
  #Install latest versions of devtools and testthat
  - Rscript -e 'install.packages(c("devtools", "testthat"))'

  #Install packages from github
  - Rscript -e 'devtools::install_github("usgs-r/gsplot")'
  - Rscript -e 'devtools::install_github("jimhester/covr")'
  - Rscript -e 'Sys.setenv(TZ="UTC")'

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
  - cat '/home/travis/build/USGS-R/repgen/repgen.Rcheck/00check.log'

notifications:
  email:
    on_success: change
    on_failure: change
