# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: objective-c
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github usgs-r/gsplot#398
  - ./travis-tool.sh install_github jimhester/covr

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'covr::coveralls()'
  
after_failure:
  - ./travis-tool.sh dump_logs  

notifications:
  email:
    on_success: change
    on_failure: change
