os: Windows Server 2012

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

clone_folder: c:\build

install:
  - ps: Bootstrap

environment:
  NOT_CRAN: "true"

build_script: 
  - build.cmd Build
  - ps: Start-FileDownload 'https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-windows.msi' -FileName 'C:\build\pandoc.msi'
  - msiexec /i C:\build\pandoc.msi /qn /log c:\build\pandoc-install.log INSTALLLOCATION=C:\pandoc
  - travis-tool.sh install_deps
  

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: '**pandoc-install.log'
    name: Logs
	  