os: Windows Server 2012

init:
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  - ps: |
        Start-FileDownload 'https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-windows.msi' -FileName 'C:\pandoc.msi'
        msiexec /i C:\pandoc.msi ALLUSERS=1 APPLICATIONFOLDER="D:\Pandoc"msiexec /qn /log C:\pandoc-install.log INSTALLLOCATION=C:\pandoc
  - SET PATH=C:\pandoc;%PATH%

install:
  - ps: Bootstrap
  - pandoc --version

environment:
  NOT_CRAN: "true"

build_script: 
  - travis-tool.sh install_deps
  

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: '*pandoc-install.log'
    name: Logs