---
version: '3.7'

services:
  aqcu-repgen:
    build: .
    image: aqcu-repgen:latest
    ports:
      - "6311:6311"

  aqcu-repgen-local-dev:
    build: .
    image: aqcu-repgen:latest
    network_mode: "host"
    ports:
      - "6311:6311"
