---
output:
  html_document:
    css: ['styles.css', 'shared-styles.css']
---
```{r setup, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
knitr::opts_knit$set(root.dir = '../..')
```
```{r child='../shared/shared-header.rmd'}
```   
***
```{r,echo=FALSE,result='asis',comment=NA,warning=FALSE}
tbl <- extremesTable(data)
# formTable <- padTable(tbl)
# cat(formTable)
if(!identical(tbl, "The dataset requested is empty.")){
  kable(tbl, align='r', row.names=FALSE)
}
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
if(!identical(tbl, "The dataset requested is empty.")){
  if(any(grepl("\\s\\*$", tbl[,"Date"])) && ncol(tbl) > 4){cat("*\\* Multiple occurrences of the same extreme on this date.*", "\n", seperator="\n")}
  else if(any(grepl("\\s\\*$", tbl[,"Date"]))){cat("*\\* Multiple occurrences of the same extreme in selected dataset.*", "\n", seperator="\n")}

  if(any(grepl("\\s\\*\\*$", tbl[,"Date"]))){cat("*\\*\\* Multiple occurrences of the same extreme in selected dataset.*", "\n", seperator="\n")}
}
```

`r if(identical(tbl, "The dataset requested is empty.")) {paste(tbl)}`

***

&nbsp;

```{r,echo=FALSE,result='asis',comment=NA,warning=FALSE}
if(!identical(tbl, "The dataset requested is empty.")){
  tbl2 <- extremesQualifiersTable(data, tbl)
  if(!is.null(tbl2) && nrow(tbl2) > 0){
    kable(tbl2, align='l', row.names=FALSE, caption = "Qualifiers")
  }
}
```