library(testthat)
library(repgen)

test_check("repgen", filter = "correctionsataglance")
test_check("repgen", filter = "dvhydrograph")
test_check("repgen", filter = "extremes")
test_check("repgen", filter = "fiveyeargwsum")
test_check("repgen", filter = "sensorreadingsummary")
test_check("repgen", filter = "sitevisitpeak")
test_check("repgen", filter = "uvhydrograph")
test_check("repgen", filter = "vdiagram")
test_check("repgen", filter = "utils-time")
test_check("repgen", filter = "utils-validation")
test_check("repgen", filter = "utils-gaps")
test_check("repgen", filter = "utils-filter")
test_check("repgen", filter = "utils-read")
test_check("repgen", filter = "utils-parse")
test_check("repgen", filter = "utils-dataFlags")
test_check("repgen", filter = "utils-fetch")
test_check("repgen", filter = "utils-limits")
test_check("repgen", filter = "utils-html")
test_check("repgen", filter = "utils-legend")
test_check("repgen", filter = "utils-plot")
test_check("repgen", filter = "reportRender")
