library(testthat)
library(repgen)

test_check("repgen", filter = "correctionsataglance")
test_check("repgen", filter = "dvhydrograph")
test_check("repgen", filter = "extremes")
test_check("repgen", filter = "fiveyeargwsum")
test_check("repgen", filter = "sensorreadingsummary")
test_check("repgen", filter = "sitevisitpeak")
test_check("repgen", filter = "uvhydrograph")
test_check("repgen", filter = "vdiagram")
test_check("repgen", filter = "utils-json")
test_check("repgen", filter = "utils-shared")
test_check("repgen", filter = "utils-time")
